### PR TITLE
Update recurly

### PR DESCRIPTION
**Pull request by aschmois**
Recurly was missing a build tool dependency also `servant-server-0.18` is not in the nightly yet.

### CODE REVIEW

**Comment by tfausak** [comment]
Looks good, but can we make it a new snapshot (2020-10-27)? I'd like to avoid mutating the snapshots if possible.

**Comment by aschmois** [comment]
> Looks good, but can we make it a new snapshot (2020-10-27)? I'd like to avoid mutating the snapshots if possible.

Is it personal preference? What if we just called the file `snapshot.yaml` so we can see diff between snapshot updates?

**Comment by tfausak** [comment]
I feel like we should go one way or the other. The upshot of not mutating the snapshot in place is that you can say `resolver: github:edutainmentlive/snapshot:2020-10-13.yaml` and always get the same thing. However if we're not likely to want that, we could use a single `snapshot.yaml` and select it based on the commit hash.

**Comment by aschmois** [comment]
Good call, not really tied to either one 🤷 my only concern is like this where we would have to essentially wait a day to push a new resolver if we made two changes in one day.

**Comment by tfausak** [comment]
Let's go ahead and just have a single snapshot file that we modify. We already pin the commit anyway, so it should be fine. If we want a slightly nicer interface on top we could tag commits and then refer to the tag, but I doubt that's necessary. Getting good diffs and easily being able to change it at any cadence is worth it I think.

**Review by tfausak — APPROVED** [review]

**Pull request merged**
