### PR TITLE
Add recurly

### PR DESCRIPTION
**Pull request by aschmois**
co-authored-by: Zach <zachary@itpro.tv>

### CODE REVIEW

**Review by saralich — APPROVED** [review]

**Comment by tfausak** [comment]
I wish there was a better way to review these changes.

``` diff
~/D/G/E/snapshot> diff -dw 2020-10-2{3,6}.yaml
1c1
< resolver: nightly-2020-10-23
---
> resolver: nightly-2020-10-26
14d13
<   - servant-server-0.18                                                         
55a55,58
> 
>   # https://github.com/EdutainmentLIVE/recurly
>   - git: https://github.com/EdutainmentLIVE/recurly
>     commit: 3285de2e10ca792a69a5c94ad09ce5e0fec8ab5e
```

What happened to `servant-server`?

**Comment by aschmois** [comment]
It was included in the latest nightly.

**Comment by tfausak** [comment]
Are you sure? I see `servant-0.18` in [nightly-2020-10-26](https://www.stackage.org/nightly-2020-10-26) but not `servant-server-0.18`.

**Comment by aschmois** [comment]
Good catch

**Pull request merged**
